name: the_green_ninja
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^2.12.0
  flame_audio: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/effects/
    - assets/images/
    - assets/images/effects/
    - assets/images/items/
    - assets/images/sprite_sheets/
    - assets/images/decorations/
